export  const certificateBodies =[
   "API Q1",
   "AS9100",
   "IACS - American Bureau of Shipping (ABS)",
   "IACS - Bureau Veritas (BV)",
   "IACS - China Classification Society (CCS)",
   "IACS - Croatian Register of Shipping (CRS)",
   "IACS - DNV",
   "IACS - Indian Register of Shipping (IRS)",
   "IACS - Korean Register of Shipping (KR)",
   "IACS - Lloyd's Register (LR)",
   "IACS - Nippon Kaiji Kyokai (ClassNK)",
   "IACS - Polski Rejestr Statków (PRS)",
   "IACS - RINA Services (RINA)",
   "IACS - Russian Maritime Register of Shipping (RS)",
   "ISO 9001",
   "ISO 14001",
   "ISO 45001",
   "ISO/IEC 17020",
   "ISO/IEC 17024",
   "ISO/IEC 17025",
   "Nadcap",
   "NAS 410",
];