export const Location = [
   {
      id: 1,
      country: "United States",
      currencyCode: "USD",
      currencyName: "United States Dollar",
      chargeContactProvider: 20,
      chargeContactInspector: 15,
   },
   {
      id: 2,
      country: "Saudi Arabia",
      currencyCode: "SAR",
      currencyName: "Saudi Riyal",
      chargeContactProvider: 5,
      chargeContactInspector: 10,
   },
   {
      id: 3,
      country: "United Arab Emirates",
      currencyCode: "AED",
      currencyName: "UAE Dirham",
      chargeContactProvider: 5,
      chargeContactInspector: 10,
   },
   {
      id: 4,
      country: "Qatar",
      currencyCode: "QAR",
      currencyName: "Qatari Riyal",
      chargeContactProvider: 20,
      chargeContactInspector: 15,
   },
   {
      id: 5,
      country: "Kuwait",
      currencyCode: "KWD",
      currencyName: "Kuwaiti Dinar",
      chargeContactProvider: 5,
      chargeContactInspector: 10,
   },
   {
      id: 6,
      country: "Oman",
      currencyCode: "OMR",
      currencyName: "Omani Rial",
      chargeContactProvider: 5,
      chargeContactInspector: 10,
   },
   {
      id: 7,
      country: "Bahrain",
      currencyCode: "BHD",
      currencyName: "Bahraini Dinar",
      chargeContactProvider: 5,
      chargeContactInspector: 10,
   },
   {
      id: 8,
      country: "Canada",
      currencyCode: "CAD",
      currencyName: "Canadian Dollar",
      chargeContactProvider: 5,
      chargeContactInspector: 10,
   },
   {
      id: 9,
      country: "Brazil",
      currencyCode: "BRL",
      currencyName: "Brazilian Real",
      chargeContactProvider: 5,
      chargeContactInspector: 10,
   },
   {
      id: 10,
      country: "Australia",
      currencyCode: "AUD",
      currencyName: "Australian Dollar",
      chargeContactProvider: 5,
      chargeContactInspector: 10,
   },
   {
      id: 11,
      country: "United Kingdom",
      currencyCode: "GBP",
      currencyName: "British Pound Sterling",
      chargeContactProvider: 5,
      chargeContactInspector: 10,
   },
   {
      id: 12,
      country: "Singapore",
      currencyCode: "SGD",
      currencyName: "Singapore Dollar",
      chargeContactProvider: 5,
      chargeContactInspector: 10,
   },
   {
      id: 13,
      country: "Norway",
      currencyCode: "NOK",
      currencyName: "Norwegian Krone",
      chargeContactProvider: 5,
      chargeContactInspector: 10,
   },
   {
      id: 14,
      country: "Netherlands",
      currencyCode: "EUR",
      currencyName: "Euro",
      chargeContactProvider: 5,
      chargeContactInspector: 10,
   },
];
